ops:
  wandb_launch_add_op:
    config:
      uri: 'https://github.com/moonshot-s/dagster-launch'
      entry_point:  ["python", "launch_test.py"]
      entity: wandb-data-science
      project: dagster_test
      # resource : kubernetes
      # queue: prod